import sys

def add_range(d, f, t):
    for i in range(f, t+1):
        d[i] = True

print "// autogenerated by {0}".format(sys.argv[0])
print "static char encoder_table[128 * 4] = {"

valid = {}
add_range(valid, 65, 90)
add_range(valid, 97, 122)
add_range(valid, 32, 33)
valid[44] = valid[46] = valid[58] = valid[59] = valid[63] = True

for i in xrange(128):
    vals = [0, 0, 0, 0]
    if i in valid:
        s = str(i)[::-1]
        for j in range(len(s)):
            vals[j] = int(s[j])
        vals[3] = len(s)
    print "   '{0:1d}', '{1:1d}', '{2:1d}', {3:2d}, // {4}".format(vals[0], vals[1], vals[2], vals[3], i)

print "};"
print "// end of autogenerated"
